spring:
  application:
    name: VEHICLE-SERVICE
  config:
    import: "optional:configserver:http://localhost:8089"
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_service_db?createDatabaseIfNotExist=true
    username: root
    password: Sithum0506
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect
