server:
  port: 8089

spring:
  cloud:
    config:
      server:
        git:
          uri: [Your Git Repository URL]
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
