server:
  port: 8089

spring:
  application:
    name: CONFIG-SERVER
    profiles:
      active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sithum1220/Highway-Ticket-Management-System.git
          clone-on-start: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
